spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/enrollctrl?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
    username: root
    password: root
  mvc:
    view:
      prefix: /pages/
      suffix: .jsp
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  redis:
    host: localhost
    port: 6379
  mail:
    default-encoding: UTF-8
    host: smtp.163.com
  profiles:
    active: prop

mybatis:
  configuration:
    mapUnderscoreToCamelCase: true # 开启驼峰命名转换法

server:
  port: 8888
  tomcat:
    uri-encoding: UTF-8

# 自定义线程池参数
enrollctrl:
  thread:
    corePoolSize: 10
    maxPoolSize: 20
    keepAliveTime: 300

logging:
  level:
    com.catchiz.enrollctrl.mapper: debug